version: "3.7"
services:
    # image project
    app:
        build:
            args:
                user: renan
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        image: laravel-app
        container_name: app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        depends_on:
            - redis
            - queue
        networks:
            - default_network

    # nginx
    nginx:
        image: nginx:alpine
        container_name: web
        restart: unless-stopped
        ports:
            - 8989:80
        volumes:
            - ./:/var/www
            - ./.docker/nginx/:/etc/nginx/conf.d/
        networks:
            - default_network

    # db mysql
    mysql:
        image: mysql:5.7.22
        container_name: db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
        volumes:
            - ./.docker/mysql/dbdata:/var/lib/mysql
        ports:
            - 3388:3306
        networks:
            - default_network

    # queue
    queue:
        build:
            args:
                user: renan
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        container_name: queue
        restart: unless-stopped
        command: "php artisan queue:work"
        volumes:
            - ./:/var/www
        depends_on:
            - redis
        networks:
            - default_network

    # redis
    redis:
        image: redis:latest
        container_name: redis
        networks:
            - default_network

networks:
    default_network:
        driver: bridge
